package app.dto;

public enum TileType {
    NORMAL_RED,
    NORMAL_YELLOW,
    NORMAL_GREEN,
    NORMAL_BLUEDARK,
    NORMAL_BROWN,
    NORMAL_BLUELIGHT,
    NORMAL_PINK,
    NORMAL_ORANGE,
    JAIL,
    JUST_VISITING,
    FREE_PARKING,
    START,
    CHANCE,
    COMMUNITY_CHEST,
    LUXURY_TAX,
    INCOME_TAX,
    RAILROAD,
    ELECTRIC_COMPANY,
    WATER_WORKS
}
